#%RAML 1.0 Trait
  headers:
    client-id: 
      type: string
      description: clientid
    client_secret:
      type: string
      description: ClientSecret
    X-Correlation-ID:
      type: string
      description: XCorrelation ID