#%RAML 1.0 DataType

properties:
  statuscode:
    type: string
    example:
      "404"
  errorType:
    type: string
    example:
      "NotFound"
  errorDescription:
    type: string
    example:
      "Method not found"